### PR TITLE
[PDI-16436]-Issues with 3 steps when exporting - importing in an EE repository

### PR DESCRIPTION
**Pull request by ArtsiomYurhevich**

### CODE REVIEW

**Comment by ArtsiomYurhevich** [comment]
@mbatchelor , @pamval Could you please take a look?

**Comment by mchen-len-son** [comment]
@pamval @mbatchelor can you please take a look?
thanks.

**Comment by mchen-len-son** [comment]
@pamval @mbatchelor can you please take a look?
thanks.

**Comment by ArtsiomYurhevich** [comment]
PDI-16436 will only be merged after code freeze (and branching happens)

**Comment by ArtsiomYurhevich** [comment]
merge it after https://github.com/pentaho/pentaho-kettle/pull/4381

**Comment by ArtsiomYurhevich** [comment]
@mbatchelor Could you please take a look?

**Comment by mchen-len-son** [comment]
@bmorrise @pamval @mbatchelor can you please take a look?
thanks

**Comment by mchen-len-son** [comment]
@bmorrise @pamval @mbatchelor can you please take a look?
thanks

**Comment by ArtsiomYurhevich** [comment]
@pamval @mbatchelor Could you please take a look?

**Pull request merged**
