### PR TITLE
[BACKLOG-35389] - pvfs s3 url is not working as expected

### PR DESCRIPTION
**Pull request by spravasahu**

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 54s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl s3-vfs
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 9m 21s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl s3-vfs
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by ssamora** [comment]
Seems ok. Please just don't forget to also check the Open URL window, where we can put a direct s3 path in it.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 5m 37s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl s3-vfs
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
