### PR TITLE
[TEST]  Adding tests for oozie impl.

### PR DESCRIPTION
**Pull request by mkambol**

### CODE REVIEW

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. mvn -fn -DrunITs=true -f impl/shim/oozie/pom.xml clean install && mvn -Dpentaho-coding-standards.version=1.0.1 -f impl/shim/oozie/pom.xml site

Cleanup:
-------
mvn build-helper:remove-project-artifact

Changed files:
==============
  impl/shim/oozie/pom.xml
  impl/shim/oozie/src/test/java/org/pentaho/big/data/impl/shim/oozie/FallbackOozieClientImplTest.java
  impl/shim/oozie/src/test/java/org/pentaho/big/data/impl/shim/oozie/OozieJobInfoDelegateTest.java
  impl/shim/oozie/src/test/java/org/pentaho/big/data/impl/shim/oozie/OozieJobInfoImplTest.java
  impl/shim/oozie/src/test/java/org/pentaho/big/data/impl/shim/oozie/OozieServiceFactoryImplTest.java
  impl/shim/oozie/src/test/java/org/pentaho/big/data/impl/shim/oozie/OozieServiceFactoryLoaderTest.java
  impl/shim/oozie/src/test/java/org/pentaho/big/data/impl/shim/oozie/OozieServiceImplTest.java










Unit test coverage change:
============
org.pentaho.big.data.impl.shim.oozie.OozieServiceFactoryImpl:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.big.data.impl.shim.oozie.OozieJobInfoDelegate:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.big.data.impl.shim.oozie.OozieJobInfoImpl:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.big.data.impl.shim.oozie.OozieServiceFactoryLoader:
 * branchPercentCoverage :100.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.big.data.impl.shim.oozie.OozieServiceImpl:
 * branchPercentCoverage :66.67%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :77.78%
 * instructionPercentCoverage :100.00%
    
org.pentaho.big.data.impl.shim.oozie.FallbackOozieClientImpl:
 * branchPercentCoverage :66.67%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :80.00%
 * instructionPercentCoverage :100.00%

**Comment by mkambol** [comment]
@brosander

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. mvn -fn -DrunITs=true -f impl/shim/oozie/pom.xml clean install && mvn -Dpentaho-coding-standards.version=1.0.1 -f impl/shim/oozie/pom.xml site

Cleanup:
-------
mvn build-helper:remove-project-artifact

Changed files:
==============
  impl/shim/oozie/pom.xml
  impl/shim/oozie/src/test/java/org/pentaho/big/data/impl/shim/oozie/FallbackOozieClientImplTest.java
  impl/shim/oozie/src/test/java/org/pentaho/big/data/impl/shim/oozie/OozieJobInfoDelegateTest.java
  impl/shim/oozie/src/test/java/org/pentaho/big/data/impl/shim/oozie/OozieJobInfoImplTest.java
  impl/shim/oozie/src/test/java/org/pentaho/big/data/impl/shim/oozie/OozieServiceFactoryImplTest.java
  impl/shim/oozie/src/test/java/org/pentaho/big/data/impl/shim/oozie/OozieServiceFactoryLoaderTest.java
  impl/shim/oozie/src/test/java/org/pentaho/big/data/impl/shim/oozie/OozieServiceImplTest.java










Unit test coverage change:
============
org.pentaho.big.data.impl.shim.oozie.OozieServiceFactoryImpl:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.big.data.impl.shim.oozie.OozieJobInfoDelegate:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.big.data.impl.shim.oozie.OozieJobInfoImpl:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.big.data.impl.shim.oozie.OozieServiceFactoryLoader:
 * branchPercentCoverage :100.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.big.data.impl.shim.oozie.OozieServiceImpl:
 * branchPercentCoverage :66.67%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :77.78%
 * instructionPercentCoverage :100.00%
    
org.pentaho.big.data.impl.shim.oozie.FallbackOozieClientImpl:
 * branchPercentCoverage :66.67%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :80.00%
 * instructionPercentCoverage :100.00%

**Comment by lucboudreau** [comment]
Nice coverage. Well done.

**Pull request merged**
