### PR TITLE
[BACKLOG-7936] Add Metadata Injection (MDI) support to the Hadoop Fil…

### PR DESCRIPTION
**Pull request by e-cuellar**
…e Output

### CODE REVIEW

**Comment by e-cuellar** [comment]
@bmorrise Please Sir!

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f kettle-plugins/hdfs/pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f kettle-plugins/hdfs/pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact

Changed files:
==============
  kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileOutputMeta.java
  kettle-plugins/hdfs/src/main/resources/org/pentaho/big/data/kettle/plugins/hdfs/trans/messages/messages_en_US.properties

License header violations:
==========================
1. Copyright year is not the current year on kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileOutputMeta.java. Found 2015. Was expecting 2016

Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileOutputMeta.java

1. Message: Unused import - org.pentaho.di.core.injection.Injection. at Line: 29 Column: 8

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f kettle-plugins/hdfs/pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f kettle-plugins/hdfs/pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact

Changed files:
==============
  kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileOutputMeta.java
  kettle-plugins/hdfs/src/main/resources/org/pentaho/big/data/kettle/plugins/hdfs/trans/messages/messages_en_US.properties

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f kettle-plugins/hdfs/pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f kettle-plugins/hdfs/pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact

Changed files:
==============
  kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileOutputMeta.java
  kettle-plugins/hdfs/src/main/resources/org/pentaho/big/data/kettle/plugins/hdfs/trans/messages/messages_en_US.properties

**Pull request merged**
