### PR TITLE
[BAD-569] Unable to load for editing ktr with HBase Input/Output step…

### PR DESCRIPTION
**Pull request by stanislau-strelchanka**
[BAD-569] Unable to load for editing ktr with HBase Input/Output steps if KDC host is unavailable - fix also for mapping exception

### CODE REVIEW

**Comment by stanislau-strelchanka** [comment]
@hudak @mkambol @mbatchelor @mchen-len-son please review

**Comment by mchen-len-son** [comment]
@pamval @mbatchelor can you please take a look?
thank you.

**Comment by pamval** [comment]
Is this the right place to perform this exception shielding?
We should catch the exceptions we know how to handle and let the others bubble up until a "top" layer. Is this location that top layer?

**Comment by stanislau-strelchanka** [comment]
@pamval I believe this is the place where we should stop it from bubbling up. Otherwise 
transformation crashes without opening. And according to David Kincade  we need avoid falling
it apart in cases when service could not be resolved (connection, mapping problems etc...).
I've discussed with @mchen-len-son current fix and we decided to refactor it a little and make sure that 
running transformation (not just opening it) with unresolved service will also provide correct information about why it is failed. Right now working on it and going to update pr soon.

**Comment by stanislau-strelchanka** [comment]
refactored, added extra logging, when transformation is executed and there are problems resolving service there will appropriate message in spoon console

**Comment by stanislau-strelchanka** [comment]
@mchen-len-son @pamval @mbatchelor please review

**Comment by stanislau-strelchanka** [comment]
@mchen-len-son @pamval @mbatchelor please review

**Pull request merged**
