### PR TITLE
[BACKLOG-34530] converts s3 to s3a for AEL PVFS files

### PR DESCRIPTION
**Pull request by dmoore62**
[STYLE] fixes trademark

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 1m
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
impl/vfs/hdfs,kettle-plugins/formats-meta
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by baudekin — APPROVED** [review]

**Review by jgminder — APPROVED** [review]

**Comment by buildguy** [comment]
### :x: Build failed in 42s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
impl/vfs/hdfs,kettle-plugins/formats-meta
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 1m 1s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
impl/vfs/hdfs,kettle-plugins/formats-meta
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 43s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
impl/vfs/hdfs,kettle-plugins/formats-meta
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 52s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
impl/vfs/hdfs,kettle-plugins/formats-meta
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1m 59s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
impl/vfs/hdfs,kettle-plugins/formats-meta
```
---
:ok_hand: All tests passed!
 
Tests run: **95**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/big-data-plugin/job/PR-2122/6/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
