### PR TITLE
[PDI-11537] Export Linked Resources: PMR Mapper and Reducer transformations not exported

### PR DESCRIPTION
**Pull request by stepanovdg**
* Checked exporting. Previous problem with paths was fixed indirectly.

### CODE REVIEW

**Comment by stepanovdg** [comment]
@dkincade Could you please take a look and decide if it`s needed?

**Comment by dkincade** [comment]
@brosander @mattyb149 @rfellows @brendan-lynch @hudak please review and/or pass on to the proper developers to review ...

**Comment by dkincade** [comment]
Sorry - processed on accident - reverted and this still needs to be reopened and reviewed ...

**Comment by brendan-lynch** [comment]
On my end this looks good, our only requirement is that it is put in the metastore as we export and import the whole metastore. As to if it is storing the correct information to properly reconstruct itself when fetched from the metastore -- someone else will have to provide some input here.

**Pull request merged**
