### PR TITLE
[PDI-12749][TEST] - PMR: Bad Results in Group-By if an entire key is filtered earlier

### PR DESCRIPTION
**Pull request by stepanovdg**
* Deleted unit test. Was discussed in http://jira.pentaho.com/browse/PDI-12749 and resulted to forbid using "GroupBy" step in singleThreaded mode.

### CODE REVIEW

**Comment by stepanovdg** [comment]
@mdamour1976 @brosander @mattyb149 Could you please take a look?

**Comment by akhayrutdinov** [comment]
@mattyb149, @brosander, @deinspanjer, @mdamour1976, @dkincade, can anybody please merge it? The test is still failing

**Comment by brosander** [comment]
@stepanovdg can we replace the single threaded wordcount test with one that tests the groupby in its correct config?

**Comment by stepanovdg** [comment]
As I can see there are at least three tests where wordcount test is tested without property "combiner_single_threaded" set to true. The default wordcount_reducer.ktr contains group by step. So it was a specific usecase(singlethreaded) and now it is forbidden.

**Pull request merged**
