### PR TITLE
[SP-6555] Update and validate in-product links in Pentaho 9.3.0.8

### PR DESCRIPTION
**Pull request by smmribeiro**
Fix SqoopExport/SqoopImport

@pentaho/tatooine_dev

### CODE REVIEW

**Review by joana-fb — APPROVED** [review]

**Comment by buildguy** [comment]
### :x: Build failed in 10m 22s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
kettle-plugins/sqoop
```
---
:ok_hand: All tests passed!
 
Tests run: **28**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-plugin-jdk11/job/PR-2550/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by smmribeiro** [comment]
Wingman passed but it had problems on docker and had to abort the run.
image

I've retriggered it.

**Comment by buildguy** [comment]
### :x: Build failed in 7m 42s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
kettle-plugins/sqoop
```
---
:ok_hand: All tests passed!
 
Tests run: **28**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-plugin-jdk11/job/PR-2550/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by smmribeiro** [comment]
The second run had the same behaviour:
image

I'm proceeding with the merge.

**Pull request merged**
