### PR TITLE
[TEST][big-data-plugin\legacy]: Increased test coverage for VfsFileChooserHelper

### PR DESCRIPTION
**Pull request by TatsianaKasiankova**
Unit tests to increase tests coverage.

### CODE REVIEW

**Comment by TatsianaKasiankova** [comment]
@brosander Hi, Please look at this PR.

**Comment by TatsianaKasiankova** [comment]
@brosander, @dkincade  Hi, Please look at this PR.

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. mvn -DrunITs=true -f legacy/pom.xml clean install && mvn -f legacy/pom.xml site

Cleanup:
-------
mvn build-helper:remove-project-artifact

Changed files:
==============
  legacy/src/main/java/org/pentaho/di/ui/vfs/VfsFileChooserHelper.java
  legacy/src/test/java/org/pentaho/di/ui/vfs/VfsFileChooserHelperTest.java










Unit test coverage change:
============
org.pentaho.di.ui.vfs.VfsFileChooserHelper:
 * branchPercentCoverage :21.43%
 * instructionPercentCoverageChange : +40.62%
 * linePercentCoverageChange : +56.51%
 * complexityPercentCoverageChange : +52.80%
 * methodPercentCoverageChange : +63.45%
    
org.pentaho.di.job.entries.hadoopjobexecutor.NoExitSecurityManager:
 * instructionPercentCoverageChange :**-1.40%**
 * branchPercentCoverageChange :**-1.56%**
 * linePercentCoverageChange :**-1.98%**
 * complexityPercentCoverageChange :**-1.54%**
 * methodPercentCoverageChange :**-3.03%**

**Comment by brosander** [comment]
org.pentaho.di.job.entries.hadoopjobexecutor.NoExitSecurityManager coverage drop looks coincidental

**Pull request merged**
