### PR TITLE
[PDI-11935]-Fixed -Now Job metrics show failed step execution when th…

### PR DESCRIPTION
**Pull request by ArtsiomYurhevich**
…e step fails. Work with enable blocking - true

### CODE REVIEW

**Comment by ArtsiomYurhevich** [comment]
@mkambol, @hudak Could you please take a look?

**Comment by kananthasayanam-rms** [comment]
@mkambol Does the big data plugins from here work for PDI 6.0 ?

**Comment by kananthasayanam-rms** [comment]
@ArtsiomYurhevich Trying to run a kettle job which has a hadoop input step from java.. I have the following dependencies added to my pom. Still getting unable to find the step error while running the code.

``` <dependency>
            <groupId>pentaho-kettle</groupId>
            <artifactId>kettle-db</artifactId>
            <version>${pentaho-db.version}</version>
        </dependency>

        <dependency>
            <groupId>pentaho-kettle</groupId>
            <artifactId>kettle-core</artifactId>
            <version>${pentaho-stable.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>commons-io</artifactId>
                    <groupId>commons-io</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>pentaho-kettle</groupId>
            <artifactId>kettle-engine</artifactId>
            <version>${pentaho-stable.version}</version>
        </dependency>

        <dependency>
            <groupId>pentaho</groupId>
            <artifactId>pentaho-big-data-kettle-plugins-hdfs</artifactId>
            <version>7.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>pentaho</groupId>
            <artifactId>pentaho-big-data-plugin</artifactId>
            <version>5.2.1.0-148</version>
        </dependency>
        <dependency>
            <groupId>pentaho-kettle</groupId>
            <artifactId>kettle-ui-swt</artifactId>
            <version>${pentaho.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>commons-io</artifactId>
                    <groupId>commons-io</groupId>
                </exclusion>
            </exclusions>
        </dependency>```

**Comment by ArtsiomYurhevich** [comment]
@kananthasayanam-rms Try to use stable 6.* version of pentaho-big-data-kettle-plugins-hdfs instead of 7.0-SNAPSHOT

**Comment by ArtsiomYurhevich** [comment]
@mkambol, @hudak, @pedrofvteixeira  Could you please take a look?

**Pull request merged**
