### PR TITLE
[BACKLOG-5229] - Create a testless big-data feature

### PR DESCRIPTION
**Pull request by rmansoor**

### CODE REVIEW

**Comment by rmansoor** [comment]
@dkincade , @CodeOnCoffee , @brosander  please review

**Comment by brosander** [comment]
@rmansoor can the normal feature include the testless one to reduce duplication?

**Comment by rmansoor** [comment]
@brosander  the change has been made. thanks

**Comment by brosander** [comment]
@rmansoor the big data plugin should probably depend on the testless feature

**Comment by rmansoor** [comment]
@brosander my mistake. copy paste error. it should be good now

**Pull request merged**
