### PR TITLE
[BAD-297] - Hadoop file output fails append to file

### PR DESCRIPTION
**Pull request by stepanovdg**
* change the vfs capabilities on the fly

### CODE REVIEW

**Comment by stepanovdg** [comment]
@brosander Could you please take a look? Updated to get/set properties.

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. mvn -fn -DrunITs=true -f api/hdfs/pom.xml clean install && mvn -f api/hdfs/pom.xml site
3. mvn -fn -DrunITs=true -f impl/shim/hdfs/pom.xml clean install && mvn -f impl/shim/hdfs/pom.xml site
4. mvn -fn -DrunITs=true -f impl/vfs/hdfs/pom.xml clean install && mvn -f impl/vfs/hdfs/pom.xml site
5. mvn -fn -DrunITs=true -f kettle-plugins/hdfs/pom.xml clean install && mvn -f kettle-plugins/hdfs/pom.xml site
6. mvn -fn -DrunITs=true -f kettle-plugins/pig/pom.xml clean install && mvn -f kettle-plugins/pig/pom.xml site

Cleanup:
-------
mvn build-helper:remove-project-artifact

Changed files:
==============
  api/hdfs/src/main/java/org/pentaho/bigdata/api/hdfs/HadoopFileSystem.java
  impl/shim/hdfs/src/main/java/com/pentaho/big/data/bundles/impl/shim/hdfs/HadoopFileSystemImpl.java
  impl/shim/hdfs/src/test/java/com/pentaho/big/data/bundles/impl/shim/hdfs/HadoopFileSystemImplTest.java
  impl/vfs/hdfs/src/main/java/org/pentaho/big/data/impl/vfs/hdfs/HDFSFileProvider.java
  impl/vfs/hdfs/src/main/java/org/pentaho/big/data/impl/vfs/hdfs/HDFSFileSystem.java
  impl/vfs/hdfs/src/test/java/org/pentaho/big/data/impl/vfs/hdfs/HDFSFileSystemTest.java
  kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileOutputMeta.java
  kettle-plugins/pig/src/it/java/org/pentaho/big/data/kettle/plugins/pig/JobEntryPigScriptExecutorIT.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File api/hdfs/src/main/java/org/pentaho/bigdata/api/hdfs/HadoopFileSystem.java
1. Message: ')' is not preceded with whitespace. at Line: 66 Column: 55







Still Broken Tests:
-----------------
org.pentaho.big.data.kettle.plugins.pig.JobEntryPigScriptExecutorIT.testRegressionTutorialLocal: java.lang.NoClassDefFoundError
```
java.lang.NoClassDefFoundError: org/pentaho/big/data/kettle/plugins/pig/NoArgJobEntryPigScriptExecutor
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.pentaho.big.data.kettle.plugins.pig.JobEntryPigScriptExecutorIT.testRegressionTutorialLocal(JobEntryPigScriptExecutorIT.java:74)

```

Unit test coverage change:
============
com.pentaho.big.data.bundles.impl.shim.hdfs.HadoopFileSystemImpl:
 * instructionPercentCoverageChange : +0.32%
 * linePercentCoverageChange : +0.55%
 * complexityPercentCoverageChange : +0.27%
 * methodPercentCoverageChange : +0.56%
    
org.pentaho.big.data.impl.vfs.hdfs.HDFSFileSystem:
 * branchPercentCoverage :100.00%
    
org.pentaho.big.data.impl.vfs.hdfs.HDFSFileProvider:
 * instructionPercentCoverageChange :**-0.40%**
    
org.pentaho.big.data.kettle.plugins.hdfs.trans.HadoopFileOutputMeta:
 * instructionPercentCoverageChange : +0.79%
 * complexityPercentCoverageChange :**-1.25%**
 * methodPercentCoverageChange :**-1.65%**

**Comment by brosander** [comment]
@stepanovdg I like the changes, could you fix the checkstyle error and add coverage for the new method in HadoopFileOutputMeta?

**Comment by stepanovdg** [comment]
Fixed checkstyle added test method. Thanks.

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. mvn -fn -DrunITs=true -f api/hdfs/pom.xml clean install && mvn -f api/hdfs/pom.xml site
3. mvn -fn -DrunITs=true -f impl/shim/hdfs/pom.xml clean install && mvn -f impl/shim/hdfs/pom.xml site
4. mvn -fn -DrunITs=true -f impl/vfs/hdfs/pom.xml clean install && mvn -f impl/vfs/hdfs/pom.xml site
5. mvn -fn -DrunITs=true -f kettle-plugins/hdfs/pom.xml clean install && mvn -f kettle-plugins/hdfs/pom.xml site
6. mvn -fn -DrunITs=true -f kettle-plugins/pig/pom.xml clean install && mvn -f kettle-plugins/pig/pom.xml site

Cleanup:
-------
mvn build-helper:remove-project-artifact

Changed files:
==============
  api/hdfs/src/main/java/org/pentaho/bigdata/api/hdfs/HadoopFileSystem.java
  impl/shim/hdfs/src/main/java/com/pentaho/big/data/bundles/impl/shim/hdfs/HadoopFileSystemImpl.java
  impl/shim/hdfs/src/test/java/com/pentaho/big/data/bundles/impl/shim/hdfs/HadoopFileSystemImplTest.java
  impl/vfs/hdfs/src/main/java/org/pentaho/big/data/impl/vfs/hdfs/HDFSFileProvider.java
  impl/vfs/hdfs/src/main/java/org/pentaho/big/data/impl/vfs/hdfs/HDFSFileSystem.java
  impl/vfs/hdfs/src/test/java/org/pentaho/big/data/impl/vfs/hdfs/HDFSFileSystemTest.java
  kettle-plugins/hdfs/src/main/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileOutputMeta.java
  kettle-plugins/hdfs/src/test/java/org/pentaho/big/data/kettle/plugins/hdfs/trans/HadoopFileOutputMetaTest.java
  kettle-plugins/pig/src/it/java/org/pentaho/big/data/kettle/plugins/pig/JobEntryPigScriptExecutorIT.java








Still Broken Tests:
-----------------
org.pentaho.big.data.kettle.plugins.pig.JobEntryPigScriptExecutorIT.testRegressionTutorialLocal: java.lang.NoClassDefFoundError
```
java.lang.NoClassDefFoundError: org/pentaho/big/data/kettle/plugins/pig/NoArgJobEntryPigScriptExecutor
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.pentaho.big.data.kettle.plugins.pig.JobEntryPigScriptExecutorIT.testRegressionTutorialLocal(JobEntryPigScriptExecutorIT.java:74)

```

Unit test coverage change:
============
org.pentaho.big.data.kettle.plugins.hdfs.trans.HadoopFileOutputMeta:
 * branchPercentCoverage :100.00%
 * instructionPercentCoverageChange : +20.08%
 * linePercentCoverageChange : +22.86%
 * complexityPercentCoverageChange : +23.75%
 * methodPercentCoverageChange : +12.64%

**Pull request merged**
