### PR TITLE
[BAD-487] - Setting caching in scanner constructor

### PR DESCRIPTION
**Pull request by brosander**

### CODE REVIEW

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. mvn -fn -DrunITs=true -f impl/shim/hbase/pom.xml clean install && mvn -f impl/shim/hbase/pom.xml site

Cleanup:
-------
mvn build-helper:remove-project-artifact

Changed files:
==============
  impl/shim/hbase/src/main/java/com/pentaho/big/data/bundles/impl/shim/hbase/table/HBaseTableImpl.java
  impl/shim/hbase/src/main/java/com/pentaho/big/data/bundles/impl/shim/hbase/table/ResultScannerBuilderImpl.java
  impl/shim/hbase/src/test/java/com/pentaho/big/data/bundles/impl/shim/hbase/table/ResultScannerBuilderImplTest.java










Unit test coverage change:
============
com.pentaho.big.data.bundles.impl.shim.hbase.table.ResultScannerBuilderImpl.new HBaseConnectionOperation() {...}:
 * linePercentCoverage :16.67%
 * methodPercentCoverage :50.00%
 * complexityPercentCoverage :50.00%
 * instructionPercentCoverage :41.38%
    
com.pentaho.big.data.bundles.impl.shim.hbase.table.HBaseTableImpl:
 * instructionPercentCoverageChange :**-0.00%**
    
com.pentaho.big.data.bundles.impl.shim.hbase.table.ResultScannerBuilderImpl:
 * linePercentCoverage :35.48%
 * methodPercentCoverage :33.33%
 * complexityPercentCoverage :33.33%
 * instructionPercentCoverage :30.16%

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman-mvn-command/1/

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f impl/shim/hbase/pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f impl/shim/hbase/pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact



Changed files:
==============
  impl/shim/hbase/src/main/java/com/pentaho/big/data/bundles/impl/shim/hbase/table/HBaseTableImpl.java
  impl/shim/hbase/src/main/java/com/pentaho/big/data/bundles/impl/shim/hbase/table/ResultScannerBuilderImpl.java
  impl/shim/hbase/src/test/java/com/pentaho/big/data/bundles/impl/shim/hbase/table/ResultScannerBuilderImplTest.java



Unit test coverage change:
============
com.pentaho.big.data.bundles.impl.shim.hbase.table.HBaseTableImpl:
 * Instruction Change :  + .10%

com.pentaho.big.data.bundles.impl.shim.hbase.table.ResultScannerBuilderImpl:
 * Complexity Change :  + 13.33%
 * Instruction Change :  + 3.49%
 * Line Change :  + 4.30%
 * Method Change :  + 13.33%

**Comment by eliofreitas** [comment]
Building pull request

**Comment by aminmkhan** [comment]
@pedrofvteixeira @pamval Please review, this looks good to go!

**Comment by pedrofvteixeira** [comment]
- triggered wingman, that gave us its 👍 
- code looks good 
- all unit tests pass successfully
- coverage increase

@pamval, your call

**Pull request merged**
