### PR TITLE
[BACKLOG-31963] Add support for s3a URLs to PDI

### PR DESCRIPTION
**Pull request by ddiroma**

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3m 2s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl legacy
```
---
:ok_hand: All tests passed!
 
Tests run: **543**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/big-data-plugin/job/PR-1862/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 2m 24s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl legacy
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 16 test(s) failed:

<details><summary><b>org.pentaho.big.data.plugins.common.ui.named.cluster.bridge.HadoopClusterDelegateBridgeImplTest.testNewNamedCluster</b> (click to expand)</summary><p>

```
org/pentaho/di/core/logging/SimpleLoggingObject
```

</p></details>

<details><summary><b>org.pentaho.big.data.plugins.common.ui.named.cluster.bridge.HadoopClusterDelegateBridgeImplTest.testEditNamedCluster</b> (click to expand)</summary><p>

```
Could not initialize class org.pentaho.big.data.plugins.common.ui.HadoopClusterDelegateImpl$$EnhancerByMockitoWithCGLIB$$d1a87910
```

</p></details>

<details><summary><b>org.pentaho.big.data.plugins.common.ui.named.cluster.bridge.HadoopClusterDelegateBridgeImplTest.testDelNamedCluster</b> (click to expand)</summary><p>

```
Could not initialize class org.pentaho.big.data.plugins.common.ui.HadoopClusterDelegateImpl$$EnhancerByMockitoWithCGLIB$$d1a87910
```

</p></details>

<details><summary><b>org.pentaho.big.data.plugins.common.ui.named.cluster.bridge.HadoopClusterDelegateBridgeImplTest.testDupeNamedCluster</b> (click to expand)</summary><p>

```
Could not initialize class org.pentaho.big.data.plugins.common.ui.HadoopClusterDelegateImpl$$EnhancerByMockitoWithCGLIB$$d1a87910
```

</p></details>

<details><summary><b>org.pentaho.big.data.plugins.common.ui.named.cluster.bridge.HadoopClusterTreeDelegateExtensionTest.testCase3NamedCluster</b> (click to expand)</summary><p>

```
[Lorg/pentaho/di/core/gui/Point;
```

</p></details>

<details><summary><b>org.pentaho.big.data.plugins.common.ui.named.cluster.bridge.HadoopClusterTreeDelegateExtensionTest.testCase1</b> (click to expand)</summary><p>

```
[Lorg/pentaho/di/core/gui/Point;
```

</p></details>

<details><summary><b>org.pentaho.big.data.plugins.common.ui.named.cluster.bridge.HadoopClusterTreeDelegateExtensionTest.testCase4NotNamedCluster</b> (click to expand)</summary><p>

```
[Lorg/pentaho/di/core/gui/Point;
```

</p></details>

<details><summary><b>org.pentaho.big.data.plugins.common.ui.named.cluster.bridge.HadoopClusterTreeDelegateExtensionTest.testSpoonProvider</b> (click to expand)</summary><p>

```
[Lorg/pentaho/di/core/gui/Point;
```

</p></details>

<details><summary><b>org.pentaho.big.data.plugins.common.ui.named.cluster.bridge.HadoopClusterTreeDelegateExtensionTest.testCase3NotNamedCluster</b> (click to expand)</summary><p>

```
[Lorg/pentaho/di/core/gui/Point;
```

</p></details>

<details><summary><b>org.pentaho.big.data.plugins.common.ui.named.cluster.bridge.HadoopClusterTreeDelegateExtensionTest.testCase4MetastoreException</b> (click to expand)</summary><p>

```
[Lorg/pentaho/di/core/gui/Point;
```

</p></details>

<details><summary><b>org.pentaho.big.data.plugins.common.ui.named.cluster.bridge.HadoopClusterTreeDelegateExtensionTest.testOneArgConstructor</b> (click to expand)</summary><p>

```
[Lorg/pentaho/di/core/gui/Point;
```

</p></details>

<details><summary><b>org.pentaho.big.data.plugins.common.ui.named.cluster.bridge.HadoopClusterTreeDelegateExtensionTest.testCase4NamedCluster</b> (click to expand)</summary><p>

```
[Lorg/pentaho/di/core/gui/Point;
```

</p></details>

<details><summary><b>org.pentaho.big.data.plugins.common.ui.named.cluster.bridge.NamedClusterBridgeImplTest.testFromOsgiNamedCluster</b> (click to expand)</summary><p>

```
org/pentaho/di/core/variables/Variables
```

</p></details>

<details><summary><b>org.pentaho.big.data.plugins.common.ui.named.cluster.bridge.NamedClusterDialogBridgeImplTest.testGetNamedCluster</b> (click to expand)</summary><p>

```
org/pentaho/di/core/variables/Variables
```

</p></details>

<details><summary><b>org.pentaho.big.data.plugins.common.ui.named.cluster.bridge.NamedClusterWidgetBridgedImplTest.testGetSelectedNamedCluster</b> (click to expand)</summary><p>

```
org/pentaho/di/core/variables/Variables
```

</p></details>

<details><summary><b>org.pentaho.big.data.kettle.plugins.hadoopcluster.ui.endpoints.HadoopClusterManagerTest.initializationError</b> (click to expand)</summary><p>

```
org/pentaho/di/core/gui/OverwritePrompter
```

</p></details>

  
Tests run: **476**, Failures: **16**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/big-data-plugin/job/PR-1862/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by ddiroma** [comment]
@bmorrise These failed tests are for Hadoop. These didn't fail during the wingman build before I squashed a second commit only to change indentation in a file and to delete a comment. No clue why they failed afterwards.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 2m 25s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl legacy
```
---
:ok_hand: All tests passed!
 
Tests run: **543**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/big-data-plugin/job/PR-1862/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
