### PR TITLE
[BACKLOG-34722] Enable namespace nomenclature on hbase input/output s…

### PR DESCRIPTION
**Pull request by tkafalas**
…teps

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 2m 14s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl kettle-plugins/hbase
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by rmansoor — APPROVED** [review]

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3m 18s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl kettle-plugins/hbase
```
---
:ok_hand: All tests passed!
 
Tests run: **77**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/big-data-plugin/job/PR-2131/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1m 45s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl kettle-plugins/hbase
```
---
:ok_hand: All tests passed!
 
Tests run: **77**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/big-data-plugin/job/PR-2131/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 2m 20s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl kettle-plugins/hbase
```
---
:ok_hand: All tests passed!
 
Tests run: **77**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/big-data-plugin/job/PR-2131/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 16s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
Command "git checkout -f d0e7fc933dd34aa4c57d51e425b0bf8d94512de1" returned status code 128:
stdout: 
stderr: fatal: reference is not a tree: d0e7fc933dd34aa4c57d51e425b0bf8d94512de1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1m 37s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl kettle-plugins/hbase
```
---
:ok_hand: All tests passed!
 
Tests run: **77**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/big-data-plugin/job/PR-2131/6/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 18s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
Command "git checkout -f d0e7fc933dd34aa4c57d51e425b0bf8d94512de1" returned status code 128:
stdout: 
stderr: fatal: reference is not a tree: d0e7fc933dd34aa4c57d51e425b0bf8d94512de1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 2m 36s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl kettle-plugins/hbase
```
---
:ok_hand: All tests passed!
 
Tests run: **77**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/big-data-plugin/job/PR-2131/8/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 17s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
Command "git checkout -f b15b8bd48f16130616d33a5b35bc9cb4aeeb352f" returned status code 128:
stdout: 
stderr: fatal: reference is not a tree: b15b8bd48f16130616d33a5b35bc9cb4aeeb352f
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 2m 58s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl kettle-plugins/hbase
```
---
:ok_hand: All tests passed!
 
Tests run: **77**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/big-data-plugin/job/PR-2131/10/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
