### PR TITLE
[BAD-491]: NullPointerException error appears when user trying to save a new named cluster (or save changes in existed named cluster after edit)

### PR DESCRIPTION
**Pull request by TatsianaKasiankova**
There are fix and a bit refactoring to avoid code duplication and cover methods editNamedCluster/createNamedCluster with a couple of unit tests.

### CODE REVIEW

**Comment by TatsianaKasiankova** [comment]
@brosander Hi, please review the PR.

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f kettle-plugins/mapreduce/pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f kettle-plugins/mapreduce/pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact

Changed files:
==============
  kettle-plugins/mapreduce/src/main/java/org/pentaho/big/data/kettle/plugins/mapreduce/ui/entry/pmr/JobEntryHadoopTransJobExecutorController.java
  kettle-plugins/mapreduce/src/test/java/org/pentaho/big/data/kettle/plugins/mapreduce/ui/entry/pmr/JobEntryHadoopTransJobExecutorControllerTest.java

Unit test coverage change:
============
org.pentaho.big.data.kettle.plugins.mapreduce.ui.entry.pmr.JobEntryHadoopTransJobExecutorController:
 * Branch Change :  + 5.67%
 * Complexity Change :  + 7.62%
 * Instruction Change :  + 6.86%
 * Line Change :  + 7.81%
 * Method Change :  + 10.57%

License header violations:
==========================
1. Copyright year is not the current year on kettle-plugins/mapreduce/src/main/java/org/pentaho/big/data/kettle/plugins/mapreduce/ui/entry/pmr/JobEntryHadoopTransJobExecutorController.java. Found 2015. Was expecting 2016

**Comment by TatsianaKasiankova** [comment]
@brosander Hi, please review the PR. Updated Copyright year

**Comment by shmaher2** [comment]
Hi

How can I become a contributor. I would like to contribute to Fixed Text Input plugin and add functionality which will permit to read from so called binary files fields of type int, long, double in big and little endianness.

Regards,
Alexandru Prodan

**Comment by brosander** [comment]
@shmaher2 thanks for your interest! :smile:

The easiest way to contribute a plugin would probably be to create your own repository (you could use https://github.com/pentaho/pentaho-mongodb-plugin as a template if you want it to be an OSGi bundle or https://github.com/brosander/kettle-plugins/tree/master/ftl if you want to do a legacy Kettle plugin)

From there, you should be able to create an input step plugin, dialog, etc.  Once you're ready for others to use it, you'd need to put the archive somewhere for them to download (https://bintray.com/ offers free artifact hosting) and then add it to the marketplace (https://github.com/pentaho/marketplace-metadata/blob/master/marketplace.xml).

**Comment by brosander** [comment]
@TatsianaKasiankova queued up another wingman run

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f kettle-plugins/mapreduce/pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f kettle-plugins/mapreduce/pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact

Changed files:
==============
  kettle-plugins/mapreduce/src/main/java/org/pentaho/big/data/kettle/plugins/mapreduce/ui/entry/pmr/JobEntryHadoopTransJobExecutorController.java
  kettle-plugins/mapreduce/src/test/java/org/pentaho/big/data/kettle/plugins/mapreduce/ui/entry/pmr/JobEntryHadoopTransJobExecutorControllerTest.java

Unit test coverage change:
============
org.pentaho.big.data.kettle.plugins.mapreduce.ui.entry.pmr.JobEntryHadoopTransJobExecutorController:
 * Branch Change :  + 5.67%
 * Complexity Change :  + 7.62%
 * Instruction Change :  + 6.86%
 * Line Change :  + 7.81%
 * Method Change :  + 10.57%

**Pull request merged**
