### PR TITLE
[PPP-4829] Upgrade Rhino on PRD and PDI

### PR DESCRIPTION
**Pull request by abryant-hv**
[PPP-4829] Upgrade Rhino on PRD and PDI

[PPP-4829]: https://hv-eng.atlassian.net/browse/PPP-4829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 1m 29s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by peterrinehart — APPROVED** [review]

**Comment by buildguy** [comment]
### :x: Build failed in 2m 24s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 2m 11s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 27m 40s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.big.data.kettle.plugins.kafka.KafkaConsumerInputTest.testSubTransStatuses</b> (click to expand)</summary><p>

```
expected:<[Stopped]> but was:<[Running]>
```

</p></details>

<details><summary><b>org.pentaho.amazon.AbstractAmazonJobExecutorTest.testGetS3FileObjectPath_validPath</b> (click to expand)</summary><p>

```
expected:</[]s3/emr/hive> but was:</[build/wingman/workspace/maintenance/wingman/builds/pentaho.big-data-plugin.PR-2461/legacy-amazon/s3:/]s3/emr/hive>
```

</p></details>

  
Tests run: **1278**, Failures: **2**, Skipped: **2** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-plugin/job/PR-2461/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
