### PR TITLE
[BACKLOG-35959] Add drag drop capabilities to File Browser.

### PR DESCRIPTION
**Pull request by tkafalas**

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 5m 6s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
impl/vfs/hdfs,kettle-plugins/browse,s3-vfs
```
---
:ok_hand: All tests passed!
 
Tests run: **125**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-plugin/job/PR-2431/1/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by peterrinehart — APPROVED** [review]

**Comment by buildguy** [comment]
### :x: Build failed in 5m 50s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
impl/vfs/hdfs,kettle-plugins/browse,s3-vfs
```
---
:ok_hand: All tests passed!
 
Tests run: **125**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-plugin/job/PR-2431/2/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 4m 33s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
impl/vfs/hdfs,kettle-plugins/browse,s3-vfs
```
---
:ok_hand: All tests passed!
 
Tests run: **125**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-plugin/job/PR-2431/3/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 5m 31s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
impl/vfs/hdfs,kettle-plugins/browse,s3-vfs
```
---
:ok_hand: All tests passed!
 
Tests run: **125**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-plugin/job/PR-2431/4/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 6m 5s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
impl/vfs/hdfs,kettle-plugins/browse,s3-vfs
```
---
:ok_hand: All tests passed!
 
Tests run: **125**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-plugin/job/PR-2431/5/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 5m 8s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
impl/vfs/hdfs,kettle-plugins/browse,s3-vfs
```
---
:ok_hand: All tests passed!
 
Tests run: **125**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-plugin/job/PR-2431/7/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 9s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
impl/vfs/hdfs,kettle-plugins/browse,s3-vfs
```
---
:ok_hand: All tests passed!
 
Tests run: **125**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-plugin/job/PR-2431/9/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by ddiroma — APPROVED** [review]

**Pull request merged**
