### PR TITLE
[PDI-13589] Corrupt Repo Export for Pentaho MapReduce jobs with Repos…

### PR DESCRIPTION
**Pull request by ivanpogodin**
…itory by Reference links
@mattyb149 , could you review it?

### CODE REVIEW

**Comment by mattyb149** [comment]
@mdamour1976 Can you take a look at this? It is the PMR version of a case you worked on (BACKLOG-179). I'm worried the logic might violate some assumptions made about only one of dir/ref/file being set (the comment above the changes says so). Thanks!

**Comment by ivanpogodin** [comment]
@mattyb149 , @mdamour1976 ,
Tests are not added. Refactoring is required to do it.

**Comment by ivanpogodin** [comment]
Commit is updated: https://github.com/pentaho/big-data-plugin/pull/419/files#diff-e13bd8435aab720875655bedfb07be1eL181
@mattyb149 , @mdamour1976 , could you review it?

**Comment by ivanpogodin** [comment]
backport to 5.4: https://github.com/pentaho/big-data-plugin/pull/427

**Comment by ivanpogodin** [comment]
@mattyb149 , @mdamour1976 , could you review it?

**Pull request merged**
