### PR TITLE
[BACKLOG-3894]Serialize Sqoop Named Cluster

### PR DESCRIPTION
**Pull request by hudak**
Add named cluster properties as extra attributes in xml/repo for when metastore is unavailable or named cluster is unused

### CODE REVIEW

**Comment by hudak** [comment]
http://10.100.11.222:8080/job/wingman-mvn/116/console

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. mvn -fn -DrunITs=true -f kettle-plugins/sqoop/pom.xml clean install && mvn -f kettle-plugins/sqoop/pom.xml site

Cleanup:
-------
mvn build-helper:remove-project-artifact

Changed files:
==============
  kettle-plugins/sqoop/src/main/java/org/pentaho/big/data/kettle/plugins/sqoop/AbstractSqoopJobEntry.java
  kettle-plugins/sqoop/src/main/java/org/pentaho/big/data/kettle/plugins/sqoop/SqoopConfig.java
  kettle-plugins/sqoop/src/main/java/org/pentaho/big/data/kettle/plugins/sqoop/SqoopExportConfig.java
  kettle-plugins/sqoop/src/main/java/org/pentaho/big/data/kettle/plugins/sqoop/SqoopExportJobEntry.java
  kettle-plugins/sqoop/src/main/java/org/pentaho/big/data/kettle/plugins/sqoop/SqoopImportConfig.java
  kettle-plugins/sqoop/src/main/java/org/pentaho/big/data/kettle/plugins/sqoop/SqoopImportJobEntry.java
  kettle-plugins/sqoop/src/main/java/org/pentaho/big/data/kettle/plugins/sqoop/ui/AbstractSqoopJobEntryController.java
  kettle-plugins/sqoop/src/main/java/org/pentaho/big/data/kettle/plugins/sqoop/ui/AbstractSqoopJobEntryDialog.java
  kettle-plugins/sqoop/src/main/java/org/pentaho/big/data/kettle/plugins/sqoop/ui/SwtLabelOrLink.java
  kettle-plugins/sqoop/src/test/java/org/pentaho/big/data/kettle/plugins/sqoop/PersistentPropertyChangeListener.java
  kettle-plugins/sqoop/src/test/java/org/pentaho/big/data/kettle/plugins/sqoop/PropertyFiringObjectTest.java
  kettle-plugins/sqoop/src/test/java/org/pentaho/big/data/kettle/plugins/sqoop/SqoopConfigTest.java
  kettle-plugins/sqoop/src/test/java/org/pentaho/big/data/kettle/plugins/sqoop/util/MockitoAutoBean.java
  legacy/src/test/java/org/pentaho/di/job/entries/helper/PersistentPropertyChangeListener.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File kettle-plugins/sqoop/src/main/java/org/pentaho/big/data/kettle/plugins/sqoop/AbstractSqoopJobEntry.java
1. Message: '{' is not preceded with whitespace. at Line: 372 Column: 65

File kettle-plugins/sqoop/src/main/java/org/pentaho/big/data/kettle/plugins/sqoop/ui/AbstractSqoopJobEntryController.java
1. Message: Using a static member import should be avoided - org.pentaho.big.data.kettle.plugins.job.BlockableJobConfig.JOB_ENTRY_NAME. at Line: 70 Column: None
2. Message: Using a static member import should be avoided - org.pentaho.big.data.kettle.plugins.sqoop.SqoopConfig.COMMAND_LINE. at Line: 71 Column: None
3. Message: Using a static member import should be avoided - org.pentaho.big.data.kettle.plugins.sqoop.SqoopConfig.TABLE. at Line: 72 Column: None


License header violations:
==========================

1. kettle-plugins/sqoop/src/test/java/org/pentaho/big/data/kettle/plugins/sqoop/util/MockitoAutoBean.java








Unit test coverage change:
============
org.pentaho.big.data.kettle.plugins.sqoop.SqoopConfig:
 * branchPercentCoverage :57.14%
 * linePercentCoverage :95.90%
 * methodPercentCoverage :97.32%
 * complexityPercentCoverage :95.51%
 * instructionPercentCoverage :96.47%
    
org.pentaho.big.data.kettle.plugins.sqoop.ArgumentWrapper:
 * branchPercentCoverage :36.36%
 * linePercentCoverage :46.15%
 * methodPercentCoverage :44.44%
 * complexityPercentCoverage :27.59%
 * instructionPercentCoverage :49.48%
    
org.pentaho.big.data.kettle.plugins.sqoop.SqoopUtils:
 * branchPercentCoverage :10.87%
 * linePercentCoverage :13.62%
 * methodPercentCoverage :23.81%
 * complexityPercentCoverage :10.00%
 * instructionPercentCoverage :23.95%
    
org.pentaho.big.data.kettle.plugins.sqoop.SqoopExportConfig:
 * linePercentCoverage :97.96%
 * methodPercentCoverage :95.00%
 * complexityPercentCoverage :95.00%
 * instructionPercentCoverage :96.95%
    
org.pentaho.big.data.kettle.plugins.sqoop.SqoopImportConfig:
 * linePercentCoverage :92.17%
 * methodPercentCoverage :98.06%
 * complexityPercentCoverage :96.19%
 * instructionPercentCoverage :84.87%
    
org.pentaho.big.data.kettle.plugins.sqoop.SqoopUtils.new Comparator() {...}:
 * branchPercentCoverage :100.00%
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%

**Comment by hudak** [comment]
@mkambol

**Comment by mkambol** [comment]
Can you cleanup the checkstyle errors?

**Comment by hudak** [comment]
yes, preparing it now

**Pull request merged**
