### PR TITLE
[PDI-14768] - When HDFS has files with spaces, some PDI component hav…

### PR DESCRIPTION
**Pull request by andrei-viaryshka**
…e strange/odd behavior

* remove unnecessary decode/encode calls
* update unit test

### CODE REVIEW

**Comment by andrei-viaryshka** [comment]
@brosander @hudak Could you please review?

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. mvn -fn -DrunITs=true -f impl/vfs/hdfs/pom.xml clean install && mvn -f impl/vfs/hdfs/pom.xml site

Cleanup:
-------
mvn build-helper:remove-project-artifact

Changed files:
==============
  impl/vfs/hdfs/src/main/java/org/pentaho/big/data/impl/vfs/hdfs/HDFSFileObject.java
  impl/vfs/hdfs/src/test/java/org/pentaho/big/data/impl/vfs/hdfs/HDFSFileObjectTest.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File impl/vfs/hdfs/src/main/java/org/pentaho/big/data/impl/vfs/hdfs/HDFSFileObject.java
1. Message: Unused import - java.net.URLDecoder. at Line: 35 Column: 8
2. Message: Unused import - java.net.URLEncoder. at Line: 36 Column: 8









Unit test coverage change:
============
org.pentaho.big.data.impl.vfs.hdfs.HDFSFileObject:
 * instructionPercentCoverageChange :**-0.28%**

**Comment by andrei-viaryshka** [comment]
@brosander @hudak fixed checkstyle violations

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. mvn -fn -DrunITs=true -f impl/vfs/hdfs/pom.xml clean install && mvn -f impl/vfs/hdfs/pom.xml site

Cleanup:
-------
mvn build-helper:remove-project-artifact

Changed files:
==============
  impl/vfs/hdfs/src/main/java/org/pentaho/big/data/impl/vfs/hdfs/HDFSFileObject.java
  impl/vfs/hdfs/src/test/java/org/pentaho/big/data/impl/vfs/hdfs/HDFSFileObjectTest.java










Unit test coverage change:
============
org.pentaho.big.data.impl.vfs.hdfs.HDFSFileObject:
 * instructionPercentCoverageChange :**-0.28%**

**Pull request merged**
