### PR TITLE
[BAD-1946] Add EMR versions 5.36 and 7.0 to available EMR Release ver…

### PR DESCRIPTION
**Pull request by ddiroma**
…sions to Amazon Hive and Amazon EMR job executor job entries

### CODE REVIEW

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :warning: Build finished in 37m 17s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl legacy-amazon
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 4 test(s) failed:

<details><summary><b>org.pentaho.amazon.AbstractAmazonJobExecutorControllerTest.testPopulateReleases_getValidCountOfEnumElements</b> (click to expand)</summary><p>

```
expected:<32> but was:<34>
```

</p></details>

<details><summary><b>org.pentaho.amazon.AbstractAmazonJobExecutorControllerTest.testPopulateReleases_addNewEmrReleaseToReleasesList</b> (click to expand)</summary><p>

```
expected:<33> but was:<35>
```

</p></details>

<details><summary><b>org.pentaho.amazon.AbstractAmazonJobExecutorControllerTest.testPopulateReleases_setEmrReleaseToFirstElementFromEmrReleasesList</b> (click to expand)</summary><p>

```
expected:<emr-[5.11].0> but was:<emr-[7.0].0>
```

</p></details>

<details><summary><b>org.pentaho.amazon.AbstractAmazonJobExecutorControllerTest.testPopulateReleases_setFirstEmrReleaseInJobEntry</b> (click to expand)</summary><p>

```
expected:<emr-[5.11].0> but was:<emr-[7.0].0>
```

</p></details>

  
Tests run: **67**, Failures: **4**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-plugin/job/PR-2565/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 26m 40s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl legacy-amazon
```
---
:ok_hand: All tests passed!
 
Tests run: **67**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-plugin/job/PR-2565/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by ddiroma** [comment]
10.2 PR: https://github.com/pentaho/big-data-plugin/pull/2568
10.2.0.0 PR: https://github.com/pentaho/big-data-plugin/pull/2567

**Pull request merged**
