### PR TITLE
[BACKLOG-6873]: Regression: NPE appears after clicking OK button if Hadoop Cluster is not chosen in "HBase Row Decoder" step

### PR DESCRIPTION
**Pull request by TatsianaKasiankova**
There are a fix of NPE and unit test on it.
Also added checks for the cases when user is trying to save/delete Mapping into HBase but there is no any selected named cluster on MappingEditor. Changes are only on UI so no unit tests for it.

### CODE REVIEW

**Comment by TatsianaKasiankova** [comment]
@brosander Hi, Bryan
Could you please review the PR.

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. mvn -fn -DrunITs=true -f impl/shim/hbase/pom.xml clean install && mvn -Dpentaho-coding-standards.version=1.0.4 -f impl/shim/hbase/pom.xml site
3. mvn -fn -DrunITs=true -f kettle-plugins/hbase/pom.xml clean install && mvn -Dpentaho-coding-standards.version=1.0.4 -f kettle-plugins/hbase/pom.xml site

Cleanup:
-------
mvn build-helper:remove-project-artifact

Changed files:
==============
  impl/shim/hbase/src/main/java/com/pentaho/big/data/bundles/impl/shim/hbase/HBaseServiceImpl.java
  impl/shim/hbase/src/test/java/com/pentaho/big/data/bundles/impl/shim/hbase/HBaseServiceImplTest.java
  kettle-plugins/hbase/src/main/java/org/pentaho/big/data/kettle/plugins/hbase/mapping/MappingEditor.java
  kettle-plugins/hbase/src/main/resources/org/pentaho/big/data/kettle/plugins/hbase/mapping/messages/messages_en_US.properties










Unit test coverage change:
============
com.pentaho.big.data.bundles.impl.shim.hbase.connectionPool.HBaseConnectionPool:
 * branchPercentCoverageChange :**-1.28%**
 * complexityPercentCoverageChange :**-2.04%**

**Comment by lucboudreau** [comment]
@brosander In this case, the code introduced in ``MappingEditor`` was [not tested](http://sonar.pentaho.com:9000/drilldown/measures/54221?metric=new_overall_coverage&period=3). Is this the same issue as ENGOPS-1773?

**Comment by brosander** [comment]
@lucboudreau the mapping editor is an swt component that didn't have any existing tests.  I was under the impression that we didn't think retrofitting swt code for unit tests was mandatory for bug fixes.

**Comment by brosander** [comment]
The issue I found was with subfloor projects.  If maven has a similar issue I'll look into it.

@brosander<https://github.com/brosander> In this case, the code introduced in MappingEditor was not tested<http://sonar.pentaho.com:9000/drilldown/measures/54221?metric=new_overall_coverage&period=3>. Is this the same issue as ENGOPS-1773?

-

**Comment by lucboudreau** [comment]
I thought about it and it's probably not related. I read the code in ``MappingEditor`` and didn't pick up on SWT. I didn't realize the ``Composite`` superclass is in SWT.

**Pull request merged**
