### PR TITLE
[BACKLOG-36830] - Kafka Enhancements (Plug-in Release)

### PR DESCRIPTION
**Pull request by lsaikrishna89**

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 2m 13s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl kettle-plugins/kafka
```
---
:ok_hand: All tests passed!
 
Tests run: **53**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-plugin/job/PR-2436/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 2m 46s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl kettle-plugins/kafka
```
---
:ok_hand: All tests passed!
 
Tests run: **53**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-plugin/job/PR-2436/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1m 59s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl kettle-plugins/kafka
```
---
:ok_hand: All tests passed!
 
Tests run: **53**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-plugin/job/PR-2436/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1m 55s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl kettle-plugins/kafka
```
---
:ok_hand: All tests passed!
 
Tests run: **53**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-plugin/job/PR-2436/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1m 39s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl kettle-plugins/kafka
```
---
:ok_hand: All tests passed!
 
Tests run: **53**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-plugin/job/PR-2436/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1m 48s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl kettle-plugins/kafka
```
---
:ok_hand: All tests passed!
 
Tests run: **53**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-plugin/job/PR-2436/6/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1m 41s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl kettle-plugins/kafka
```
---
:ok_hand: All tests passed!
 
Tests run: **53**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-plugin/job/PR-2436/7/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1m 42s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl kettle-plugins/kafka
```
---
:ok_hand: All tests passed!
 
Tests run: **53**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-plugin/job/PR-2436/9/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by peterrinehart — APPROVED** [review]

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1m 51s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl kettle-plugins/kafka
```
---
:ok_hand: All tests passed!
 
Tests run: **53**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-plugin/job/PR-2436/10/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
