### PR TITLE
[PPP-4815] - Vulnerable Component: Ini4j 0.5.1

### PR DESCRIPTION
**Pull request by renato-s**
@andreramos89 
@bcostahitachivantara 
@smmribeiro

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 26s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl assemblies/pmr-libraries
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 33s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl assemblies/pmr-libraries
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]
Looks good!

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 1s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl assemblies/pmr-libraries
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
