### PR TITLE
Add MDI to MapReduce Input/Output

### PR DESCRIPTION
**Pull request by AlexanderBuloichik**

### CODE REVIEW

**Comment by AlexanderBuloichik** [comment]
Only MDI with tests was added. Is there any sense to create tests for non-metadata classes for this commit ?

**Comment by lucboudreau** [comment]
Considering the drop of 50% in HadoopEnterMeta, I'd say yes, it is.

**Comment by AlexanderBuloichik** [comment]
@lucboudreau I'm not sure that percentage calculated correctly. I added 6 very simple methods to HadoopEnterMeta and all they have unit tests.

**Comment by lucboudreau** [comment]
Yeah I think it'll be ok. The change is in integration tests only. The unit tests should cover it, and the combined coverage in Sonar will include both.

**Pull request merged**
