### PR TITLE
[BACKLOG-32646] Update "Amazon EMR job executor" job entry to use enh…

### PR DESCRIPTION
**Pull request by ddiroma**
…anced VFS browser for browsing and selecting local files

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 2m 33s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl legacy
```
---
:ok_hand: All tests passed!
 
Tests run: **543**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/big-data-plugin/job/PR-1939/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by ddiroma** [comment]
@cseverino789

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3m 36s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl legacy
```
---
:ok_hand: All tests passed!
 
Tests run: **543**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/big-data-plugin/job/PR-1939/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 2m 31s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl legacy
```
---
:ok_hand: All tests passed!
 
Tests run: **543**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/big-data-plugin/job/PR-1939/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
