### PR TITLE
[CHECKSTYLE]: Fixes for checkstyle voilations in legacy.

### PR DESCRIPTION
**Pull request by TatsianaKasiankova**
This is just a fix for several checkstyle violations.

### CODE REVIEW

**Comment by TatsianaKasiankova** [comment]
@dkincade  Hi, please review.

**Comment by dkincade** [comment]
@lucboudreau - will the wingman server work on this project?

**Comment by lucboudreau** [comment]
@dkincade On its way. http://10.100.11.222:8080/job/wingman-mvn/42/console

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. mvn -DskipTests -f legacy/pom.xml clean install && mvn -f legacy/pom.xml site

Cleanup:
-------
mvn build-helper:remove-project-artifact

Changed files:
==============
  legacy/src/main/java/org/pentaho/di/core/hadoop/HadoopConfigurationBootstrap.java
  legacy/src/main/java/org/pentaho/di/job/entries/oozie/OozieJobExecutorConfig.java
  legacy/src/main/java/org/pentaho/di/ui/job/entries/hadoopjobexecutor/JobEntryHadoopJobExecutorDialog.java
  legacy/src/main/java/org/pentaho/di/ui/job/entries/hadooptransjobexecutor/JobEntryHadoopTransJobExecutorDialog.java
  legacy/src/main/java/org/pentaho/di/ui/job/entries/sqoop/SqoopExportJobEntryController.java

Checkstyle violations:
======================
No errors found

License header violations:
==========================
No violations found

**Comment by dkincade** [comment]
Perfect - thanks!

**Pull request merged**
