### PR TITLE
[PDI-19598] - "Create File" step does not create a file in the folder when S3(VFS) path is given.

### PR DESCRIPTION
**Pull request by bcostahitachivantara**
Please review this PR without merge until we get approval to push changes to master due 9.4 release code freeze.
@ssamora 

@smmribeiro 
@andreramos89 
@renato-s

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 1m 32s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl s3-vfs
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 45s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl s3-vfs
```
---
:ok_hand: All tests passed!
 
Tests run: **66**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-plugin-11/job/PR-2360/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by bcostahitachivantara** [comment]
Please squash the commits

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3m 12s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl s3-vfs
```
---
:ok_hand: All tests passed!
 
Tests run: **66**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-plugin-11/job/PR-2360/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
