### PR TITLE
[BAD-281] - Build CDH54 shim

### PR DESCRIPTION
**Pull request by mtseu**
register new CDH54 which is to replace CDH53
Dear reviewer, please merge only after the https://github.com/pentaho/pentaho-hadoop-shims/pull/255 has been merged.

@brosander @mattyb149 would you mind to review

### CODE REVIEW

**Comment by mtseu** [comment]
is supposed to be followed by the https://github.com/pentaho/pentaho-big-data-ee/pull/76 PR

**Comment by mtseu** [comment]
@lgrill-pentaho FYI (see http://jira.pentaho.com/browse/BAD-286)

**Comment by stepanovdg** [comment]
https://github.com/pentaho/big-data-plugin/pull/423 should be merged instead of this pull-request

**Comment by mattyb149** [comment]
Closing in favor of #423

**Pull request closed without merging**
