### PR TITLE
[BACKLOG-37368] Update bouncycastle dependencies to remove old version

### PR DESCRIPTION
**Pull request by peterrinehart**
and match latest used by license manager.

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 3m 20s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl assemblies/pmr-libraries
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3m 59s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl assemblies/pmr-libraries
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 2m 29s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl assemblies/pmr-libraries
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 1m 24s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl assemblies/pmr-libraries
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 48s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl assemblies/pmr-libraries
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Review by ddiroma — APPROVED** [review]

**Pull request merged**
