### PR TITLE
[PDI-18845] Text File Input Step does not handle Mac EOL <CR> only

### PR DESCRIPTION
**Pull request by tkafalas**

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 1m 57s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl kettle-plugins/hdfs
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 2m 39s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl kettle-plugins/hdfs
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 54s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl kettle-plugins/hdfs
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by ddiroma** [comment]
Build is failing because wingman is picking up 9.2.0.0-SNAPSHOT artifacts instead of 9.3. Approved and will merge.

**Pull request merged**
