### PR TITLE
[BACKLOG-29504] Added shim identifier property to Sqoop advance options

### PR DESCRIPTION
**Pull request by angel-ramoscardona**

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1m 4s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl kettle-plugins/sqoop
```
---
:ok_hand: All tests passed!
 
Tests run: **26**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/big-data-plugin/job/PR-1915/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1m 3s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl kettle-plugins/sqoop
```
---
:ok_hand: All tests passed!
 
Tests run: **26**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/big-data-plugin/job/PR-1915/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1m 8s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl kettle-plugins/sqoop
```
---
:ok_hand: All tests passed!
 
Tests run: **26**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/big-data-plugin/job/PR-1915/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by angel-ramoscardona** [comment]
Just a draft PR

**Pull request closed without merging**
