### PR TITLE
[SP-2859] - Backport of PDI-8984 - Sorting fields on the HBase Output…

### PR DESCRIPTION
**Pull request by YuryBY**
… Create/Edit Mappings tab Causes Data Conversion Error (5.4 Suite)

@mchen-len-son, @pamval, here is backport of https://github.com/pentaho/big-data-plugin/commit/bc6abbc228ed70e7aafcf0099ca1ecf8fcf541c4 to 5.4. Thanks.

### CODE REVIEW

**Comment by mchen-len-son** [comment]
@YuryBY please, update copyright year

**Comment by YuryBY** [comment]
@mchen-len-son, have done

**Comment by mchen-len-son** [comment]
@Yury, there are also checkstyle violations:

File D:\src\big-data-plugin\src\org\pentaho\hbase\mapping\MappingEditor.java
Error Description	Line
Line has trailing spaces.	89
Line has trailing spaces.	1130
Line has trailing spaces.	1131
Line has trailing spaces.	1140
Line has trailing spaces.	1142

**Comment by YuryBY** [comment]
@mchen-len-son, have updated

**Pull request merged**
