### PR TITLE
[SP-6428] - Backport of PDI-19732 - Transformation connecting to S3 fails when using URL s3n://s3n/{s3_bucket_name} (9.3 Suite)

### PR DESCRIPTION
**Pull request by andreramos89**
Original PR: https://github.com/pentaho/big-data-plugin/pull/2468

@smmribeiro 
@bcostahitachivantara 
@renato-s

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 4m 49s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl legacy-amazon
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by andreramos89** [comment]
Wingman build is failling because https://github.com/pentaho/pentaho-kettle/pull/9097 needs to be merged for it to compile.

**Comment by buildguy** [comment]
### :x: Build failed in 2m 28s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl legacy-amazon
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]
Consistent with the original PRs (https://github.com/pentaho/big-data-plugin/pull/2468 and https://github.com/pentaho/big-data-plugin/pull/2475).

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 10m 8s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl legacy-amazon
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
