### PR TITLE
Issues/9.1/backlog 29332

### PR DESCRIPTION
**Pull request by NJtwentyone**

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 1m 23s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl s3-vfs
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by NJtwentyone** [comment]
depends on https://github.com/pentaho/pentaho-kettle/pull/7365. will rebase and kickoff new wingman, once PR is merged.

**Comment by buildguy** [comment]
### :x: Build failed in 14s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
Command "git checkout -f cafcbdc54717a44204b69c5e2b555a18f1e0a384" returned status code 128:
stdout: 
stderr: fatal: reference is not a tree: cafcbdc54717a44204b69c5e2b555a18f1e0a384
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 5m 40s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl s3-vfs
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.s3.vfs.S3FileObjectTest.testDoGetOutputStream</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **594**, Failures: **1**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/big-data-plugin/job/PR-2046/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 3m 7s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl s3-vfs
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.s3.vfs.S3FileObjectTest.testDoGetOutputStream</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **594**, Failures: **1**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/big-data-plugin/job/PR-2046/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 4m 19s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl s3-vfs
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.s3.vfs.S3FileObjectTest.testDoGetOutputStream</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **594**, Failures: **1**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/big-data-plugin/job/PR-2046/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3m 33s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl s3-vfs
```
---
:ok_hand: All tests passed!
 
Tests run: **594**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/big-data-plugin/job/PR-2046/6/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by NJtwentyone** [comment]
DO NOT MERGE

**Comment by buildguy** [comment]
### :warning: Build finished in 3m 21s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl s3-vfs
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.s3.vfs.S3FileObjectTest.testDoGetOutputStream</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **594**, Failures: **1**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/big-data-plugin/job/PR-2046/7/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 5m 42s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl s3-vfs
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.s3.vfs.S3FileObjectTest.testDoGetOutputStream</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **594**, Failures: **1**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/big-data-plugin/job/PR-2046/8/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 5m 56s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl s3-vfs
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.s3.vfs.S3FileObjectTest.testDoGetOutputStream</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **594**, Failures: **1**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/big-data-plugin/job/PR-2046/9/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 3m 30s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl s3-vfs
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.s3.vfs.S3FileObjectTest.testDoGetOutputStream</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **594**, Failures: **1**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/big-data-plugin/job/PR-2046/10/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 3s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 17s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl s3-vfs
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 48s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl s3-vfs
```
---
:ok_hand: All tests passed!
 
Tests run: **594**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/big-data-plugin/job/PR-2046/13/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 51s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl s3-vfs
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 56s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl s3-vfs
```
---
:ok_hand: All tests passed!
 
Tests run: **594**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/big-data-plugin/job/PR-2046/15/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by NJtwentyone** [comment]
There was a difference in the test results between local and on Jenkins. In jenkins server, the mocking framework wasn't calling the constructor which populated a member variable class. Now, I explicitly supply the class. This however exposed a corner case I forgot. that will be addressed in https://github.com/pentaho/pentaho-kettle/pull/7366

**Pull request merged**
