### PR TITLE
Backlog 39124

### PR DESCRIPTION
**Pull request by angel-ramoscardona**

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3m 55s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
assemblies/kafka-plugin,kettle-plugins/kafka
```
---
:ok_hand: All tests passed!
 
Tests run: **53**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-plugin/job/PR-2496/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3m 37s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
assemblies/kafka-plugin,kettle-plugins/kafka
```
---
:ok_hand: All tests passed!
 
Tests run: **53**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-plugin/job/PR-2496/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 7m
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
assemblies/kafka-plugin,kettle-plugins/hadoop-cluster/ui,kettle-plugins/kafka
```
---
:ok_hand: All tests passed!
 
Tests run: **78**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-plugin/job/PR-2496/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 8m 15s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
assemblies/kafka-plugin,kettle-plugins/hadoop-cluster/ui,kettle-plugins/kafka
```
---
:ok_hand: All tests passed!
 
Tests run: **78**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-plugin/job/PR-2496/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by rsleem — APPROVED** [review]

**Pull request merged**
