### PR TITLE
[BACKLOG-32845] SWT Gtk widget in Hadoop Job Executor Step loads extr…

### PR DESCRIPTION
**Pull request by angelorod**

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1m 9s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl kettle-plugins/mapreduce
```
---
:ok_hand: All tests passed!
 
Tests run: **76**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/big-data-plugin/job/PR-1968/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by lucboudreau** [comment]
Needs a test in:
https://github.com/pentaho/big-data-plugin/blob/master/kettle-plugins/mapreduce/src/test/java/org/pentaho/big/data/kettle/plugins/mapreduce/ui/entry/pmr/JobEntryHadoopTransJobExecutorControllerTest.java

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1m 4s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl kettle-plugins/mapreduce
```
---
:ok_hand: All tests passed!
 
Tests run: **76**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/big-data-plugin/job/PR-1968/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1m 8s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl kettle-plugins/mapreduce
```
---
:ok_hand: All tests passed!
 
Tests run: **76**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman2.pentaho.net/job/projects/job/big-data-plugin/job/PR-1968/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by angelorod** [comment]
Luc mentioned adding a unit test to JobEntryHadoopTransJobExecutorControllerTest.java. That unit test is used to test JobEntryHadoopTransJobExecutorController. Not the class that I modified, which is JobEntryHadoopJobExecutorController. There is no unit test for the class I modified. Given that I'm unfamiliar with the controller, designing and creating a new unit test class would be a significant effort.

**Pull request merged**
