### PR TITLE
[PPP-4481] - Upgrade h2 library

### PR DESCRIPTION
**Pull request by rmansoor**

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 7m 57s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
assemblies/pmr-libraries,kettle-plugins/common/job,legacy,legacy-amazon
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 29m 58s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl \
assemblies/pmr-libraries,kettle-plugins/common/job,legacy,legacy-amazon
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 1m 7s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by smmribeiro** [comment]
This PR is no longer valid:
- has conflicts as current code already includes these changes
- [PPP-4481](https://hv-eng.atlassian.net/browse/PPP-4481) is closed (fixed) since 2022 (March)
Closing.

**Pull request closed without merging**
