### PR TITLE
[PDI-9392] HBase input step filter column family by prefix

### PR DESCRIPTION
**Pull request by stepanovdg**
* Added possibility to create filters for Key field and for Tupple Mapping
* Added StartsFrom operator

### CODE REVIEW

**Comment by stepanovdg** [comment]
required https://github.com/pentaho/pentaho-hadoop-shims/pull/278

**Comment by stepanovdg** [comment]
@brosander @dmoran64  Could you please take a look?

**Comment by dkincade** [comment]
@brosander @mattyb149  @mtseu please review...

**Comment by dkincade** [comment]
Before we continue working on this issue - I need to understand why this would be required for the 6.0.0 GA release. If it is not, then let's put the pull requests on hold until after the 6.0.0 GA release.

**Comment by bkemper-pentaho** [comment]
David

These are pretty big items which we couldn't easily SP for a couple big customers, so we'd really like to get these in quickly.  It's a pretty significant gap


Sent from my iPhone

On Sep 11, 2015, at 7:55 PM, David Kincade <notifications@github.com<mailto:notifications@github.com>> wrote:


Before we continue working on this issue - I need to understand why this would be required for the 6.0.0 GA release. If it is not, then let's put the pull requests on hold until after the 6.0.0 GA release.

-

**Comment by mattyb149** [comment]
The word "Tuple" is misspelled in some methods/variables as "Tupple". Also, is it possible to squash all the code changes into one commit, and keep a separate commit for CheckStyle? This would allow us to review all the code changes at once, without the CheckStyle stuff. Thanks!

**Comment by stepanovdg** [comment]
Start working on squashing and misspelling.
ValueMeta was used  as method getTypeDesc() is not api method of the ValueMetaInterface.

**Comment by mattyb149** [comment]
ValueMeta gets that method from ValueMetaBase, please use that instead, thanks!

**Comment by stepanovdg** [comment]
Updated

**Comment by stepanovdg** [comment]
updated

**Pull request merged**
