### PR TITLE
[SP-2003] Backport of PDI-13589 - Corrupt Repo Export for Pentaho Map…

### PR DESCRIPTION
**Pull request by ivanpogodin**
…Reduce jobs with "Repository by Reference" links (5.4 Suite)
This is a 5.4. backport of https://github.com/pentaho/big-data-plugin/pull/419
No tests added. Refactoring is required.
@mattyb149 , @mdamour1976 , could you review it?

### CODE REVIEW

**Comment by akhayrutdinov** [comment]
@mattyb149, @m-a-hall, @mdamour1976, review it please at earliest convenience. This ticket is included in the August SP, that ends this week

**Comment by ivanpogodin** [comment]
@mattyb149, @m-a-hall, @mdamour1976, review it please at earliest convenience. This ticket is included in the August SP, that ends this week

**Comment by mattyb149** [comment]
@ivanpogodin Have you tested the other usages of these fields? Such as exporting/saving a file from the repo back to disk, then opening that?  And importing that file then saving to a repo?  I'm confident this change fixes the Export case (which is the original issue), but I want to make sure it doesn't break other logic. Some code may assume if one of (reference, path/name, filename) are set, that it handles the job/trans a certain way, and won't check to see if any of the others are set. This may not be a problem, but I'd like to know that other paths were tested besides the original export issue.

Thanks!

@akhayrutdinov @mbradbury2014 FYI

**Comment by ivanpogodin** [comment]
@mattyb149 
Yes, save-import-export are checked - the fields are processed without any condition.
And I checked it manually. They were performed correctly.

@akhayrutdinov @mbradbury2014 FYI

**Pull request merged**
